spring:
  main:
    web-application-type: none
    banner-mode: off

  ai:
    mcp:
      server:
        enabled: true
        name: smarthub-mcp-server
        version: 0.0.1
        type: SYNC
        stdio: true
      client:
        enabled: true
        name: smarthub-mcp-client
        version: 0.0.1
        type: SYNC

    logging:
      file:
        name: logs/mcp-server.log
      level:
        root: INFO