package com.example.mini_project_ss14.mcp.validator;

import org.springframework.stereotype.Component;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@Component
public class SafeSqlValidator {
    private static final Set<String> ALLOWED_TABLES = Set.of(
            "deliveries",
            "incidents"
    );

    private static final Pattern TABLE_PATTERN = Pattern.compile(
            "\\b(?:FROM|JOIN)\\s+([a-zA-Z_][a-zA-Z0-9_]*)",
            Pattern.CASE_INSENSITIVE
    );

    private static final Pattern FORBIDDEN_KEYWORDS = Pattern.compile(
            "\\b(?:INSERT|UPDATE|DELETE|DROP|ALTER|CREATE|TRUNCATE|"
                    + "GRANT|REVOKE|MERGE|UPSERT|CALL|DO|COPY|"
                    + "EXECUTE|VACUUM|ANALYZE|REFRESH|REINDEX|"
                    + "COMMENT)\\b",
            Pattern.CASE_INSENSITIVE
    );

    private static final Pattern FROM_CLAUSE = Pattern.compile(
            "\\bFROM\\s+(.+?)(?=\\bWHERE\\b|\\bGROUP\\s+BY\\b|\\bORDER\\s+BY\\b|\\bLIMIT\\b|$)",
            Pattern.CASE_INSENSITIVE | Pattern.DOTALL
    );

    /**
     * Validates that a SQL query is a safe, read-only query
     * against the allowed SmartHub tables.
     *
     * @param sql SQL generated by the LLM
     * @throws IllegalArgumentException if the SQL is unsafe
     */
    public void validate(String sql) {
        if (sql == null || sql.isBlank()) {
            throw new IllegalArgumentException("SQL query must not be empty");
        }

        String normalized = normalize(sql);

        validateSingleStatement(normalized);
        validateSelectOnly(normalized);
        validateForbiddenKeywords(normalized);
        validateNoCommaJoins(normalized);
        validateTables(normalized);
    }

    private String normalize(String sql) {
        String normalized = sql.trim();

        normalized = normalized
                .replaceAll("(?s)/\\*.*?\\*/", " ")
                .replaceAll("(?m)--[^\\r\\n]*", " ");

        if (normalized.contains("$$")) {
            throw new IllegalArgumentException(
                    "Dollar-quoted SQL is not allowed"
            );
        }

        return normalized.trim();
    }

    private void validateSingleStatement(String sql) {
        if (sql.contains(";")) {
            throw new IllegalArgumentException(
                    "Multiple SQL statements are not allowed"
            );
        }
    }

    private void validateSelectOnly(String sql) {
        if (!sql.matches("(?is)^SELECT\\b.*")) {
            throw new IllegalArgumentException(
                    "Only SELECT queries are allowed"
            );
        }
    }

    private void validateForbiddenKeywords(String sql) {
        String withoutStrings = sql.replaceAll(
                "'(?:''|[^'])*'",
                " "
        );

        Matcher matcher = FORBIDDEN_KEYWORDS.matcher(withoutStrings);

        if (matcher.find()) {
            throw new IllegalArgumentException(
                    "Forbidden SQL operation: " + matcher.group()
            );
        }
    }

    private void validateNoCommaJoins(String sql) {
        Matcher matcher = FROM_CLAUSE.matcher(sql);

        if (matcher.find()) {
            String fromClause = matcher.group(1);

            String beforeFirstJoin = fromClause.split("(?i)\\bJOIN\\b")[0];

            if (beforeFirstJoin.contains(",")) {
                throw new IllegalArgumentException(
                        "Comma-style joins are not allowed; use explicit JOIN"
                );
            }
        }
    }

    private void validateTables(String sql) {
        Matcher matcher = TABLE_PATTERN.matcher(sql);

        boolean foundTable = false;

        while (matcher.find()) {
            foundTable = true;

            String tableName = matcher.group(1).toLowerCase();

            if (!ALLOWED_TABLES.contains(tableName)) {
                throw new IllegalArgumentException(
                        "Table is not allowed: " + tableName
                );
            }
        }

        if (!foundTable) {
            throw new IllegalArgumentException(
                    "Query must reference an allowed table"
            );
        }
    }
}